### ISSUE TITLE
Various todo items

### ISSUE THREAD

**Issue by nanotee** [nanotee/nvim-lua-guide#45]
- [x] Explain how to reload modules with `package.loaded['modname'] = nil`
    - maybe mention `plenary`'s reload function?
- [x] Automated testing for plugins. A link to [plenary's test harness](https://github.com/nvim-lua/plenary.nvim/#plenarytest_harness) is probably sufficient
    - This exists as well: [notomo/vusted](https://github.com/notomo/vusted)
- [x] LuaRocks packages. `packer` has support for them, so I want to at least mention that in the guide

**Comment by matu3ba** [comment]
link really good lua intro like [this one](https://github.com/medwatt/Notes/blob/main/Lua/Lua_Quick_Guide.ipynb)?
(only async missing)

**Comment by nanotee** [comment]
Yup, saw that guide earlier, looks really good! I've added it in https://github.com/nanotee/nvim-lua-guide/commit/6bd5fde20ec46f13e3f3d4df4abd330af9bf616f
